name: Stats

on:
  push:
    branches: [main]

jobs:
  build:
    if: github.repository == 'MarioIncCorp/mini_action' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Run script
        run: python ./Roadmap/stats.py

      - name: Commit and Push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Update stats
          commit_user_name: Mario LC [GitHub Actions]
          commit_user_email: mlopezc2099@gmail.com
          commit_author: mlopezc2099 <mlopezc2099@gmail.com>